In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant(15)
b = tf.constant(20)
print(a + b)

tf.Tensor(35, shape=(), dtype=int32)


In [3]:
x = np.random.rand(100).astype(np.float32)
print(x)

[0.50464255 0.5925431  0.83647424 0.2414629  0.64342594 0.07111526
 0.15659973 0.9685808  0.4428901  0.8663162  0.33227983 0.08064537
 0.98347926 0.10045546 0.7084484  0.18164027 0.8269507  0.4198912
 0.64802355 0.80187887 0.26076    0.10563082 0.15407766 0.9361615
 0.13935067 0.333581   0.7610502  0.9822693  0.06961653 0.52075475
 0.8296619  0.42479867 0.96608055 0.35577145 0.15257715 0.81560403
 0.56572413 0.31510112 0.5582042  0.5312976  0.33629668 0.48600075
 0.385972   0.2402918  0.67250645 0.8724507  0.18944155 0.08357283
 0.63590926 0.34205094 0.3459219  0.49039227 0.13120456 0.66880035
 0.9116601  0.05938415 0.43379048 0.6607579  0.19458032 0.11658236
 0.76929224 0.8399217  0.32826287 0.47507197 0.86127687 0.35511586
 0.45053124 0.85200524 0.8518189  0.7474228  0.8597833  0.75052035
 0.89547783 0.0596192  0.84013104 0.521655   0.91186666 0.78044677
 0.6536881  0.16618319 0.08543418 0.59954005 0.34908253 0.21848063
 0.17277835 0.03607909 0.7563097  0.04482274 0.791693   0.167923

In [4]:
y = x * 0.2 + 0.2

In [5]:
w = tf.Variable(tf.random.normal([1]))

In [6]:
b = tf.Variable(tf.zeros([1]))

In [7]:
def mse_loss():
  ypred = w * x + b
  loss = tf.reduce_mean(tf.square(ypred - y))
  return loss

In [8]:
optimizer = tf.keras.optimizers.Adam()

In [9]:
for step in range(5000):
  optimizer.minimize(mse_loss, var_list=[w, b])
  if step % 500 == 0:
    print(step, w.numpy(), b.numpy())

0 [1.034619] [-0.00099999]
500 [0.73121685] [-0.08902757]
1000 [0.50820416] [0.03282038]
1500 [0.34196907] [0.12310241]
2000 [0.24932039] [0.17329575]
2500 [0.21195954] [0.19352496]
3000 [0.20183043] [0.19900897]
3500 [0.20015457] [0.1999163]
4000 [0.20000619] [0.1999967]
4500 [0.2000009] [0.1999995]


In [11]:
pip install torch

     -------------------------------------- 167.3/167.3 MB 2.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [12]:
import torch
import numpy as np

In [13]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [14]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [15]:
x_ones = torch.ones_like(x_data)
print("One Tensor:\n", x_ones)
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(x_rand)

One Tensor:
 tensor([[1, 1],
        [1, 1]])
tensor([[0.2333, 0.2518],
        [0.4243, 0.4650]])


In [16]:
shape = (2, 3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3, 4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.6672, 0.1974, 0.1215],
        [0.3623, 0.3720, 0.3845]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.9618, 0.0629, 0.1761, 0.1491],
        [0.8027, 0.5852, 0.8806, 0.2687],
        [0.1892, 0.9195, 0.3269, 0.8667]])


device(type='cpu')

In [17]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

In [18]:
tensor = torch.ones(4, 4)
print("Tensor:\n", tensor)
tensor1 = torch.zeros(4, 4)
print("Tensor1:\n", tensor1)
tensor2 = torch.cat([tensor, tensor1])
print("Tensor2:\n", tensor2)

Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Tensor1:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tensor2:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [19]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [21]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
